-- MySQL Script generated by MySQL Workbench
-- Sun Jun 16 00:01:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbnb` DEFAULT CHARACTER SET utf8 ;
USE `airbnb` ;

-- -----------------------------------------------------
-- Table `airbnb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(40) NULL,
  `nombre` VARCHAR(45) NULL,
  `edad` INT NULL,
  `telefono` INT NULL,
  `sexo` VARCHAR(2) NULL,
  `direccion` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  `estado` VARCHAR(30) NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`anfitrion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`anfitrion` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`anfitrion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `idioma` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`Estado` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`Estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`Departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(30) NULL,
  `habitaciones` INT NULL,
  `baños` INT NULL,
  `camas` INT NULL,
  `noches_minimas` INT NULL,
  `precio_noche` INT NULL,
  `checkin` TIME NULL,
  `checkout` TIME NULL,
  `ubicacion` VARCHAR(45) NULL,
  `id_anfitrion` INT NOT NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Departamento_anfitrion1_idx` (`id_anfitrion` ASC),
  INDEX `fk_Departamento_Estado1_idx` (`id_estado` ASC),
  CONSTRAINT `fk_Departamento_anfitrion1`
    FOREIGN KEY (`id_anfitrion`)
    REFERENCES `airbnb`.`anfitrion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departamento_Estado1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `airbnb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`experiencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`experiencia` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`experiencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `personas` INT NULL,
  `precio` INT NULL,
  `duracion` TIME NULL,
  `idioma` VARCHAR(45) NULL,
  `id_anfitron` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_experiencia_anfitrion1_idx` (`id_anfitron` ASC),
  CONSTRAINT `fk_experiencia_anfitrion1`
    FOREIGN KEY (`id_anfitron`)
    REFERENCES `airbnb`.`anfitrion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`amenidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`amenidades` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`amenidades` (
  `id_amenidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  PRIMARY KEY (`id_amenidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`Pago` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`Pago` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_tarjeta` VARCHAR(45) NULL,
  `tipo_tarjeta` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `fecha` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`Reservacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`Reservacion` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`Reservacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `checkin` DATE NULL,
  `checkout` DATE NULL,
  `numero_personas` INT NULL,
  `fecha` DATETIME NULL,
  `id_usuario` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  `id_pago` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Reservacion_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_Reservacion_Departamento1_idx` (`id_departamento` ASC),
  INDEX `fk_Reservacion_Pago1_idx` (`id_pago` ASC),
  CONSTRAINT `fk_Reservacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `airbnb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_Departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `airbnb`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservacion_Pago1`
    FOREIGN KEY (`id_pago`)
    REFERENCES `airbnb`.`Pago` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`amenidades_has_Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`amenidades_has_Departamento` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`amenidades_has_Departamento` (
  `id_amenidad` INT NOT NULL,
  `id_departamento` INT NOT NULL,
  PRIMARY KEY (`id_amenidad`, `id_departamento`),
  INDEX `fk_amenidades_has_Departamento_Departamento1_idx` (`id_departamento` ASC),
  INDEX `fk_amenidades_has_Departamento_amenidades1_idx` (`id_amenidad` ASC),
  CONSTRAINT `fk_amenidades_has_Departamento_amenidades1`
    FOREIGN KEY (`id_amenidad`)
    REFERENCES `airbnb`.`amenidades` (`id_amenidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_amenidades_has_Departamento_Departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `airbnb`.`Departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
